apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-database-data2
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-storagepool-cluster
  volumeMode: Filesystem

