apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-database
  labels:
    app: counter-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-database
  template:
    metadata:
      labels:
        app: counter-database
    spec:
      containers:
        - name: counter-database
          image: registry.redhat.io/rhel8/postgresql-15:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: counter-database-data2
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-name
      volumes:
        - name: counter-database-data2
          persistentVolumeClaim:
            claimName: counter-database-data2